### ISSUE TITLE
История цифр поехала :)

### ISSUE THREAD

**Issue by ghost** [efekta/it_planeta#1]

**Comment by efekta** [comment]
А там фсе к zalala поехало, адаптива неть, а на десктоп так и надо https://www.figma.com/file/51FwA6kwmhzqK1C47rNkzM/desctop_tablet?node-id=269%3A0

**Comment by efekta** [comment]
> _No description provided._

**Comment by efekta** [comment]
> _No description provided._

А там фсе к zalala поехало, адаптива неть, : ) а на десктоп так и надо https://www.figma.com/file/51FwA6kwmhzqK1C47rNkzM/desctop_tablet?node-id=269%3A0

**Comment by efekta** [comment]
долбаный гит, как тут писать ахах

**Comment by NSzzz** [comment]
> долбаный гит, как тут писать ахах

дак потому что не в гите надо писать!

**Comment by efekta** [comment]
.
